---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  esClusterName: "prod"
  esVersion: "7.16.0"

---
apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Kibana
metadata:
  name: kibana
spec:
  replicas: 1
  esCluster:
    host: http://elasticsearch-master:9200
    esVersion: 7.16.0
    clusterName: "prod"

---


apiVersion: logging.logging.opstreelabs.in/v1beta1
kind: Fluentd
metadata:
  name: fluentd
spec:
  esCluster:
    host: elasticsearch-master
  indexNameStrategy: namespace_name
