---
apiVersion: v1
kind: Namespace
metadata:
  name: es-ns


---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-db
  namespace: es-ns
spec:
  version: 8.13.4
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false



---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-ui
  namespace: es-ns
spec:
  version: 8.13.4
  count: 2
  elasticsearchRef:
    name: "es-db"
